FROM library/node:alpine as builder

COPY *.js *.json /build/
COPY src/ /build/src/

RUN cd /build && \
    npm ci && \
    npm run build

FROM library/nginx:1.28.0-alpine

COPY nginx.frontend.conf         /etc/nginx/conf.d/default.conf
COPY www/index.html              /var/www/html/
COPY --from=builder /build/www/* /var/www/html/